/**Each new term in the Fibonacci sequence is generated by adding the previous
 two terms. By starting with 1 and 2, the first 10 terms will be:

 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 By considering the terms in the Fibonacci sequence whose values do not
 exceed four million, find the sum of the even-valued terms.*/

var i = 1;
var j = 1;
var k = 1;
var sum = 0;
while(i+j<200){
	k=i;
	i+=j;
	j=k;
	if(i%2===0) {
		sum+=i;
	}
}
console.log("The sum of all even Fibonacci numbers under 4,000,000 is:")
console.log(i);